Repository Namo-log/Android, pull requests merged in 2024-08, with the labels that each got.

#279 [Refactor/278] remoteConfig로 baseUrl 사용, 모듈 수정
  app/src/main/java/com/mongmong/namo/data/datasource/auth/RemoteAuthDataSource.kt
  app/src/main/java/com/mongmong/namo/data/remote/AnonymousApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/AuthApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/ReissuanceApiService.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/AuthRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/AuthRepository.kt
  app/src/main/java/com/mongmong/namo/presentation/config/ApplicationClass.kt
  app/src/main/java/com/mongmong/namo/presentation/config/RemoteConfigWrapper.kt
  app/src/main/java/com/mongmong/namo/presentation/config/XAccessTokenInterceptor.kt
  app/src/main/java/com/mongmong/namo/presentation/di/AppModule.kt
  app/src/main/java/com/mongmong/namo/presentation/di/NetworkModule.kt
  app/src/main/java/com/mongmong/namo/presentation/di/ServiceModule.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/login/AuthViewModel.kt
Labels: ♻️ refactor

#280 [Style/278] remoteConfig를 android_baseurl로 변경
  app/src/main/java/com/mongmong/namo/presentation/config/RemoteConfigWrapper.kt
  app/src/main/java/com/mongmong/namo/presentation/di/NetworkModule.kt
Labels: 🎨 style

#281 🐛 Fix: baseurl을 가져오지 못하는 경우, BuildConfig에서 조회
  app/src/main/java/com/mongmong/namo/presentation/config/RemoteConfigWrapper.kt
Labels: 🐛 bug

#282 [Refactor/272] BaseFragment, BaseActivity 추가 및 적용
  app/src/main/java/com/mongmong/namo/presentation/config/BaseActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/config/BaseFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/MainActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/CategoryActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/CategoryDetailFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/CategoryEditActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/CategorySettingFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/custom/CustomFontFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/custom/CustomFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/custom/CustomMyFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/custom/CustomPaletteFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/custom/CustomSettingFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryImageDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/MoimMemoDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/PersonalDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupCalendarActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupInfoActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/calendar/GroupCalendarMonthFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/diary/MoimDiaryActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/schedule/GroupScheduleActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/schedule/GroupScheduleMemberActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/calendar/CalendarMonthFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleDialogBasicFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleDialogCategoryFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/MapActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/login/TermsFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/FirstFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/FourthFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/OnBoardingActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/OnBoardingFifthFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/OnBoardingFirstFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/OnBoardingFourthFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/OnBoardingFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/OnBoardingSecondFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/OnBoardingThirdFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/SecondFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/onBoarding/adapter/OnboardingVPAdapter.kt
  app/src/main/res/layout/activity_category.xml
  app/src/main/res/layout/activity_group_schedule_member.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_schedule.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_custom_font.xml
Labels: ♻️ refactor

#289 [Fix/288] 개인 기록 이미지 추가되지 않는 버그 수정
  app/src/main/java/com/mongmong/namo/data/datasource/diary/RemoteDiaryDataSource.kt
  app/src/main/java/com/mongmong/namo/data/remote/DiaryApiService.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/DiaryRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/domain/model/Diary.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/DiaryRepository.kt
  app/src/main/java/com/mongmong/namo/presentation/config/RemoteConfigWrapper.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryDetailViewModel.kt
Labels: 🐛 bug, ♻️ refactor

#291 [Refactor/287] 토큰 헤더에 refreshToken 추가
  app/src/main/java/com/mongmong/namo/data/datasource/auth/RemoteAuthDataSource.kt
  app/src/main/java/com/mongmong/namo/data/remote/AuthApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/ReissuanceApiService.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/AuthRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/AuthRepository.kt
  app/src/main/java/com/mongmong/namo/presentation/config/ReissuanceTokenInterceptor.kt
  app/src/main/java/com/mongmong/namo/presentation/config/RemoteConfigWrapper.kt
  app/src/main/java/com/mongmong/namo/presentation/config/XAccessTokenInterceptor.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/login/AuthViewModel.kt
Labels: ♻️ refactor

#292 [Fix/290] 약관 동의 여부 확인 로직 수정
  app/src/main/java/com/mongmong/namo/data/datasource/auth/RemoteAuthDataSource.kt
  app/src/main/java/com/mongmong/namo/domain/model/Auth.kt
  app/src/main/java/com/mongmong/namo/presentation/config/RemoteConfigWrapper.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/login/AuthViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/login/LoginFragment.kt
Labels: 🐛 bug, ♻️ refactor

#293 [Refactor/287] 토큰 관련 파라미터 정리
  app/src/main/java/com/mongmong/namo/data/datasource/terms/RemoteTermDataSource.kt
  app/src/main/java/com/mongmong/namo/data/remote/AuthApiService.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/AuthRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/domain/model/Auth.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/AuthRepository.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/login/AuthViewModel.kt
Labels: ♻️ refactor

#302 [Refactor/301] BottomNavigation 아이콘 변경
  app/src/main/java/com/mongmong/namo/presentation/ui/MainActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/CommunityFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/shop/ShopFragment.kt
  app/src/main/res/drawable/ic_nav_community_selected.xml
  app/src/main/res/drawable/ic_nav_community_unselected.xml
  app/src/main/res/drawable/ic_nav_custom_selected.xml
  app/src/main/res/drawable/ic_nav_custom_unselected.xml
  app/src/main/res/drawable/ic_nav_diary_selected.xml
  app/src/main/res/drawable/ic_nav_diary_unselected.xml
  app/src/main/res/drawable/ic_nav_group_selected.xml
  app/src/main/res/drawable/ic_nav_group_unselected.xml
  app/src/main/res/drawable/ic_nav_home_selected.xml
  app/src/main/res/drawable/ic_nav_home_unselected.xml
  app/src/main/res/drawable/ic_nav_shop_selected.xml
  app/src/main/res/drawable/ic_nav_shop_unselected.xml
  app/src/main/res/drawable/selector_nav_community.xml
  app/src/main/res/drawable/selector_nav_diary.xml
  app/src/main/res/drawable/selector_nav_group.xml
  app/src/main/res/drawable/selector_nav_shop.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_custom.xml
  app/src/main/res/layout/fragment_shop.xml
  app/src/main/res/menu/nav_menu.xml
  app/src/main/res/navigation/nav_bottomnav.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 style, ♻️ refactor

#300 🐛 Fix: 블랙 색상 변경
  app/src/main/res/values/colors.xml
Labels: 🎨 style
