Repository Namo-log/Android, pull requests merged in 2024-07, with the labels that each got.

#260 [Fix/259] 기록/모임기록 버그 수정
  app/src/main/java/com/mongmong/namo/domain/model/Diary.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryDetailViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/MoimMemoDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/PersonalDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/DiaryAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/DiaryImageItemDecoration.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/GalleryListAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/MoimDiaryAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/adapter/DailyMoimRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/adapter/DailyPersonalRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/calendar/CalendarMonthFragment.kt
  app/src/main/res/drawable/ic_diary_image_delete_btn.xml
  app/src/main/res/layout/activity_moim_memo_detail.xml
  app/src/main/res/layout/activity_personal_diary_detail.xml
  app/src/main/res/layout/item_diary_item_list.xml
  app/src/main/res/layout/item_diary_list.xml
  app/src/main/res/layout/item_gallery_list.xml
Labels: 🐛 bug, ♻️ refactor

#265 [Refactor/264] 그룹 데이터바인딩
  app/src/main/java/com/mongmong/namo/domain/model/group/Group.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupCalendarActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupInfoActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/adapter/GroupListRVAdapter.kt
  app/src/main/res/layout/activity_group_info.xml
  app/src/main/res/layout/dialog_group_code.xml
  app/src/main/res/layout/fragment_group_list.xml
  app/src/main/res/layout/item_group_list.xml
Labels: ♻️ refactor

#266 [Refactor/262] 카테고리 데이터바인딩 적용
  app/src/main/java/com/mongmong/namo/data/local/entity/home/Category.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/CategoryRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/CategoryRepository.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/CategoryDetailFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/CategoryEditActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/CategorySettingFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/CategoryViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/adapter/CategoryPaletteRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/adapter/SetCategoryRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/adapter/DailyPersonalRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleDialogCategoryFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/adapter/DialogCategoryRVAdapter.kt
  app/src/main/res/layout/activity_category_edit.xml
  app/src/main/res/layout/fragment_category_detail.xml
  app/src/main/res/layout/fragment_category_setting.xml
  app/src/main/res/layout/fragment_schedule_dialog_category.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_dialog_schedule_category.xml
  app/src/main/res/values/strings.xml
Labels: ♻️ refactor

#261 [Feat/258] 기록 이미지 리팩토링, 이미지 상세보기 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mongmong/namo/data/datasource/diary/DiaryMoimPagingSource.kt
  app/src/main/java/com/mongmong/namo/data/datasource/diary/DiaryPersonalPagingSource.kt
  app/src/main/java/com/mongmong/namo/data/datasource/diary/RemoteDiaryDataSource.kt
  app/src/main/java/com/mongmong/namo/data/remote/DiaryApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/group/GroupDiaryApiService.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/DiaryRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/data/utils/RequestConverter.kt
  app/src/main/java/com/mongmong/namo/domain/model/Diary.kt
  app/src/main/java/com/mongmong/namo/domain/model/group/GroupDiary.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/DiaryRepository.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/CategoryEditActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/custom/CustomSettingFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryDetailViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryImageDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryImageItemDecoration.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/ImageDialog.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/MoimMemoDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/PersonalDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/DiaryAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/DiaryGalleryRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/DiaryRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/GalleryImageRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/ImageDetailVPAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupInfoActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/diary/ItemTouchHelperCallback.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/diary/MoimDiaryActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/diary/MoimDiaryViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/diary/adapter/MoimActivityGalleryAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/diary/adapter/MoimActivityRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/schedule/GroupScheduleActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/ConfirmDialog.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_diary_image_detail_back.xml
  app/src/main/res/drawable/ic_download.xml
  app/src/main/res/drawable/ic_moim_diary_activity_add.xml
  app/src/main/res/layout/activity_diary_image_detail.xml
  app/src/main/res/layout/activity_moim_diary.xml
  app/src/main/res/layout/activity_moim_memo_detail.xml
  app/src/main/res/layout/activity_personal_diary_detail.xml
  app/src/main/res/layout/dialog_image_full.xml
  app/src/main/res/layout/item_diary_image_detail.xml
  app/src/main/res/layout/item_diary_moim_activity.xml
  app/src/main/res/values/colors.xml
Labels: ✨ feature, ♻️ refactor

#268 [Refactor/267] 그룹 참여 리팩토링
  app/src/main/java/com/mongmong/namo/data/datasource/group/GroupDataSource.kt
  app/src/main/java/com/mongmong/namo/data/remote/group/GroupApiService.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/GroupRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/domain/model/group/Group.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/GroupRepository.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/MoimMemoDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/PersonalDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/CreateGroupDialog.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupCodeDialog.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupInfoActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/GroupViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/adapter/GroupInfoMemberRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/diary/MoimDiaryActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/BindingAdapters.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/ImageViewBindingAdapters.kt
  app/src/main/res/layout/activity_group_info.xml
  app/src/main/res/layout/activity_moim_diary.xml
  app/src/main/res/layout/activity_moim_memo_detail.xml
  app/src/main/res/layout/activity_personal_diary_detail.xml
  app/src/main/res/layout/fragment_group_list.xml
  app/src/main/res/layout/item_group_member.xml
Labels: ♻️ refactor

#271 [Refactor/256] 일정 상세 데이터바인딩 적용
  app/src/main/java/com/mongmong/namo/data/datasource/schedule/RemoteScheduleDataSource.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/CategoryRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/ScheduleRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/domain/model/group/Group.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/ScheduleRepository.kt
  app/src/main/java/com/mongmong/namo/presentation/config/Constants.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/calendar/GroupCalendarMonthFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/calendar/adapter/GroupDailyMoimRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/calendar/adapter/GroupDailyPersonalRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/schedule/GroupScheduleActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/schedule/MoimScheduleViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/adapter/DailyMoimRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/calendar/CalendarMonthFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/PersonalScheduleViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleDialogBasicFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/adapter/DailyScheduleRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/ScheduleDateConverter.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/StringConverter.kt
  app/src/main/res/drawable/bg_schedule_preview_catory_color_corner.xml
  app/src/main/res/drawable/ic_add_record.png
  app/src/main/res/drawable/ic_add_record_black.png
  app/src/main/res/drawable/ic_record.xml
  app/src/main/res/layout/activity_group_schedule.xml
  app/src/main/res/layout/activity_moim_memo_detail.xml
  app/src/main/res/layout/fragment_calendar_month.xml
  app/src/main/res/layout/fragment_group_calendar_month.xml
  app/src/main/res/layout/fragment_schedule_dialog_basic.xml
  app/src/main/res/layout/item_diary_item_list.xml
  app/src/main/res/layout/item_schedule_preview.xml
  app/src/main/res/layout/item_schedule_preview_moim.xml
  app/src/main/res/values/strings.xml
Labels: ♻️ refactor

#275 🐛 Fix: 코틀린 버전 1.8.0으로 업데이트
  .idea/kotlinc.xml
  .idea/misc.xml
  app/src/main/java/com/mongmong/namo/data/local/Converters.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryDetailViewModel.kt
  build.gradle
Labels: 🐛 bug

#276 [Refactor/273] 토큰 재발급 헤더 추가
  app/src/main/java/com/mongmong/namo/presentation/config/ApplicationClass.kt
  app/src/main/java/com/mongmong/namo/presentation/config/ReissuanceTokenInterceptor.kt
  app/src/main/java/com/mongmong/namo/presentation/di/NetworkModule.kt
  app/src/main/java/com/mongmong/namo/presentation/di/ServiceModule.kt
Labels: ♻️ refactor
