Repository Namo-log/Android, pull requests merged in 2024-11, with the labels that each got.

#331 [Feat/330] 보관함 캘린더 디자인 수정
  app/src/main/java/com/mongmong/namo/data/dto/DiaryCalendarDTO.kt
  app/src/main/java/com/mongmong/namo/data/utils/mappers/DiaryMapper.kt
  app/src/main/java/com/mongmong/namo/domain/model/DiaryModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/moim/diary/MoimDiaryViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryCalendarFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryCalendarViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/PersonalDiaryDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/PersonalDiaryViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/DiaryCalendarAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/BindingAdapters.kt
  app/src/main/res/drawable/ic_archive_diary.xml
  app/src/main/res/drawable/ic_archive_diary_small.xml
  app/src/main/res/drawable/ic_birthday.xml
  app/src/main/res/layout/item_diary_calendar_date.xml
  app/src/main/res/layout/item_moim_diary.xml
  app/src/main/res/layout/item_personal_diary.xml
Labels: ✨ feature, ♻️ refactor

#332 [Feat/327] 친구 API 연동
  app/src/main/java/com/mongmong/namo/data/datasource/friend/RemoteFriendDataSource.kt
  app/src/main/java/com/mongmong/namo/data/dto/FriendDTO.kt
  app/src/main/java/com/mongmong/namo/data/remote/FriendApiService.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/FriendRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/data/utils/mappers/FriendMapper.kt
  app/src/main/java/com/mongmong/namo/domain/model/Category.kt
  app/src/main/java/com/mongmong/namo/domain/model/Friend.kt
  app/src/main/java/com/mongmong/namo/domain/model/FriendModel.kt
  app/src/main/java/com/mongmong/namo/domain/model/MoimModel.kt
  app/src/main/java/com/mongmong/namo/domain/model/ScheduleModel.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/FriendRepository.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/ScheduleRepository.kt
  app/src/main/java/com/mongmong/namo/domain/usecases/AcceptFriendRequestUseCase.kt
  app/src/main/java/com/mongmong/namo/domain/usecases/DenyFriendRequestUseCase.kt
  app/src/main/java/com/mongmong/namo/domain/usecases/GetFriendsUseCase.kt
  app/src/main/java/com/mongmong/namo/presentation/di/DataSourceModule.kt
  app/src/main/java/com/mongmong/namo/presentation/di/RepositoryModule.kt
  app/src/main/java/com/mongmong/namo/presentation/di/ServiceModule.kt
  app/src/main/java/com/mongmong/namo/presentation/di/UseCaseModule.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/CommunityCalendarActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/alert/AlertViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/alert/FriendAlertFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/alert/MoimAlertFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/alert/adapter/FriendAlertRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/calendar/CalendarViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/calendar/CommunityCalendarMonthFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/calendar/CommunityCalendarView.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/calendar/adapter/ParticipantDailyScheduleRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/friend/AddFriendDialog.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/friend/FriendFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/friend/FriendInfoDialog.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/friend/FriendViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/moim/schedule/FriendInviteViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/BindingAdapters.kt
  app/src/main/res/drawable/img_default_moim.xml
  app/src/main/res/drawable/img_default_profile.xml
  app/src/main/res/layout/activity_moim_schedule.xml
  app/src/main/res/layout/dialog_add_friend.xml
  app/src/main/res/layout/dialog_friend_info.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/item_friend.xml
  app/src/main/res/layout/item_friend_alert.xml
  app/src/main/res/layout/item_friend_invite.xml
  app/src/main/res/layout/item_moim.xml
  app/src/main/res/layout/item_moim_alert.xml
  app/src/main/res/layout/item_schedule_preview_moim.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#335 [Fix/333] 보관함 필터명 변경, 보관함 변수명 Collection -> Archive로 변경
  app/src/main/java/com/mongmong/namo/data/datasource/diary/DiaryArchivePagingSource.kt
  app/src/main/java/com/mongmong/namo/data/dto/DiaryArchiveDTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/DiaryCalendarDTO.kt
  app/src/main/java/com/mongmong/namo/data/remote/DiaryApiService.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/DiaryRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/data/utils/mappers/DiaryMapper.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/DiaryRepository.kt
  app/src/main/java/com/mongmong/namo/presentation/state/FilterType.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryArchiveFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/DiaryImagesRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/DiaryRVAdapter.kt
  app/src/main/res/layout/fragment_diary_archive.xml
  app/src/main/res/layout/item_diary_archive.xml
  app/src/main/res/layout/item_diary_archive_image.xml
Labels: 🐛 bug, ♻️ refactor

#341 [Chore/337] 내부 저장 카테고리 색상 변경
  app/src/main/java/com/mongmong/namo/presentation/enums/CategoryColor.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/calendar/CommunityCalendarView.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/custom/CustomMyFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/custom/CustomPaletteFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/calendar/PersonalCalendarView.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/category/CategoryDetailFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/category/CategoryViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/category/adapter/CategoryPaletteRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/BindingAdapters.kt
  app/src/main/res/layout/activity_personal_diary_detail.xml
  app/src/main/res/layout/fragment_category_detail.xml
  app/src/main/res/layout/fragment_schedule_dialog_basic.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_dialog_schedule_category.xml
  app/src/main/res/layout/item_diary_archive.xml
  app/src/main/res/layout/item_moim_diary.xml
  app/src/main/res/layout/item_palette_color.xml
  app/src/main/res/layout/item_personal_diary.xml
  app/src/main/res/values/strings.xml
Labels: 🔧 chore

#342 [Refactor/340] 생성 수정 삭제 에러 핸들링
  app/src/main/java/com/mongmong/namo/data/datasource/diary/RemoteActivityDataSource.kt
  app/src/main/java/com/mongmong/namo/data/datasource/diary/RemoteDiaryDataSource.kt
  app/src/main/java/com/mongmong/namo/data/datasource/friend/RemoteFriendDataSource.kt
  app/src/main/java/com/mongmong/namo/data/datasource/schedule/RemoteScheduleDataSource.kt
  app/src/main/java/com/mongmong/namo/data/dto/ActivityDTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/AwsS3DTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/CategoryDTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/DiaryArchiveDTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/DiaryCalendarDTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/DiaryDTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/DiaryForScheduleDTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/FriendDTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/MoimDTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/ScheduleDTO.kt
  app/src/main/java/com/mongmong/namo/data/dto/TermDTO.kt
  app/src/main/java/com/mongmong/namo/data/remote/ActivityApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/DiaryApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/FriendApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/MoimApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/ScheduleApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/TermApiService.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/ActivityRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/DiaryRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/FriendRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/data/utils/common/ErrorHandler.kt
  app/src/main/java/com/mongmong/namo/domain/model/ActivityModel.kt
  app/src/main/java/com/mongmong/namo/domain/model/AuthModel.kt
  app/src/main/java/com/mongmong/namo/domain/model/BaseModel.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/ActivityRepository.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/DiaryRepository.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/FriendRepository.kt
  app/src/main/java/com/mongmong/namo/domain/usecases/diary/AddMoimDiaryUseCase.kt
  app/src/main/java/com/mongmong/namo/domain/usecases/diary/EditMoimDiaryUseCase.kt
  app/src/main/java/com/mongmong/namo/presentation/di/DataSourceModule.kt
  app/src/main/java/com/mongmong/namo/presentation/di/RepositoryModule.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/community/moim/diary/MoimDiaryViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/diary/PersonalDiaryViewModel.kt
Labels: ♻️ refactor

#345 [Feat/344] BaseFragment, BaseActivity에 토스트 띄우는 메서드 추가
  app/src/main/java/com/mongmong/namo/presentation/config/BaseActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/config/BaseFragment.kt
Labels: ✨ feature
