Repository Namo-log/Android, pull requests merged in 2024-06, with the labels that each got.

#229 [Feat/215] 인앱 업데이트 구현
  .gitignore
  app/build.gradle
  app/src/main/java/com/mongmong/namo/presentation/config/ApplicationClass.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/SplashActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/AppUpdateHelper.kt
  build.gradle
Labels: ✨ feature

#238 [Fix/237] 메인 액티비티 중복 실행 버그 수정
  app/src/main/java/com/mongmong/namo/presentation/ui/SplashActivity.kt
Labels: 🐛 bug

#241 [Fix/240] 기록 줄바꿈 수정
  app/src/main/res/layout/activity_moim_memo_detail.xml
  app/src/main/res/layout/activity_personal_diary_detail.xml
Labels: 🐛 bug

#236 [Fix/235] 캘린더 이모지 대응, 캘린더 말줄임표 삭제
  app/src/main/java/com/mongmong/namo/presentation/ui/group/calendar/GroupCalendarView.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/calendar/PersonalCalendarView.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/CustomCalendarView.kt
Labels: 🐛 bug

#244 [Refactor/232] 카카오맵 v2로 업데이트 및 장소 선택 로직 변경
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mongmong/namo/presentation/config/ApplicationClass.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/schedule/GroupScheduleActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleDialogBasicFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/MapActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/adapter/MapRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/data/KakaoAPI.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/data/KakaoPlace.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/data/Place.kt
  app/src/main/res/drawable-v24/border_round_all_stroke_main_orange.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_pin_default.png
  app/src/main/res/drawable/ic_pin_selected.png
  app/src/main/res/layout/activity_group_schedule.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/fragment_schedule_dialog_basic.xml
  app/src/main/res/layout/item_map_place.xml
  app/src/main/res/values-v26/styles.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: ♻️ refactor

#246 🐛 Fix: 캘린더 다음 달 날짜 불투명 처리 안되는 버그 수정
  app/src/main/java/com/mongmong/namo/presentation/utils/CustomCalendarView.kt
Labels: 🐛 bug

#245 [Release] 1.0.4
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mongmong/namo/presentation/config/ApplicationClass.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/SplashActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/calendar/GroupCalendarView.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/schedule/GroupScheduleActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/calendar/PersonalCalendarView.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleDialogBasicFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/MapActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/adapter/MapRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/data/KakaoAPI.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/data/KakaoPlace.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/data/Place.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/CustomCalendarView.kt
  app/src/main/res/drawable-v24/border_round_all_stroke_main_orange.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_pin_default.png
  app/src/main/res/drawable/ic_pin_selected.png
  app/src/main/res/layout/activity_group_schedule.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/activity_moim_memo_detail.xml
  app/src/main/res/layout/activity_personal_diary_detail.xml
  app/src/main/res/layout/fragment_schedule_dialog_basic.xml
  app/src/main/res/layout/item_map_place.xml
  app/src/main/res/values-v26/styles.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: :bookmark: release

#249 [Release] 1.0.4
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mongmong/namo/presentation/config/ApplicationClass.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/SplashActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/calendar/GroupCalendarView.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/schedule/GroupScheduleActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/calendar/PersonalCalendarView.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleDialogBasicFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/MapActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/adapter/MapRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/data/KakaoAPI.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/data/KakaoPlace.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/map/data/Place.kt
  app/src/main/java/com/mongmong/namo/presentation/utils/CustomCalendarView.kt
  app/src/main/res/drawable-v24/border_round_all_stroke_main_orange.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_pin_default.png
  app/src/main/res/drawable/ic_pin_selected.png
  app/src/main/res/layout/activity_group_schedule.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/activity_moim_memo_detail.xml
  app/src/main/res/layout/activity_personal_diary_detail.xml
  app/src/main/res/layout/fragment_schedule_dialog_basic.xml
  app/src/main/res/layout/item_map_place.xml
  app/src/main/res/values-v26/styles.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: :bookmark: release

#251 [Fix/250] 인앱 업데이트 시 자동로그인 호출 버그
  app/src/main/java/com/mongmong/namo/presentation/utils/AppUpdateHelper.kt
Labels: 🐛 bug

#253 [Refactor/248] 로컬 기능 사용 중지
  app/src/main/java/com/mongmong/namo/data/datasource/category/RemoteCategoryDataSource.kt
  app/src/main/java/com/mongmong/namo/data/datasource/diary/DiaryPersonalPagingSource.kt
  app/src/main/java/com/mongmong/namo/data/datasource/diary/RemoteDiaryDataSource.kt
  app/src/main/java/com/mongmong/namo/data/datasource/schedule/RemoteScheduleDataSource.kt
  app/src/main/java/com/mongmong/namo/data/remote/CategoryApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/DiaryApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/ScheduleApiService.kt
  app/src/main/java/com/mongmong/namo/data/remote/category/CategoryService.kt
  app/src/main/java/com/mongmong/namo/data/remote/schedule/ScheduleService.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/CategoryRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/DiaryRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/data/repositoriyImpl/ScheduleRepositoryImpl.kt
  app/src/main/java/com/mongmong/namo/domain/model/Category.kt
  app/src/main/java/com/mongmong/namo/domain/model/Diary.kt
  app/src/main/java/com/mongmong/namo/domain/model/Schedule.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/DiaryRepository.kt
  app/src/main/java/com/mongmong/namo/domain/repositories/ScheduleRepository.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryDetailViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/DiaryFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/PersonalDetailActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/DiaryAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/MoimDiaryAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/adapter/DailyMoimRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/adapter/DailyPersonalRVAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/calendar/CalendarMonthFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/calendar/PersonalCalendarView.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/PersonalScheduleViewModel.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/home/schedule/ScheduleDialogBasicFragment.kt
  app/src/main/res/layout/fragment_schedule_dialog_basic.xml
  app/src/main/res/layout/item_diary_item_list.xml
Labels: ♻️ refactor

#255 [Refactor/254] 일정, 기록, 카테고리 로컬 저장 코드 삭제
  app/src/main/java/com/mongmong/namo/data/datasource/diary/DiaryMoimPagingSource.kt
  app/src/main/java/com/mongmong/namo/data/datasource/diary/DiaryPersonalPagingSource.kt
  app/src/main/java/com/mongmong/namo/data/local/NamoDatabase.kt
  app/src/main/java/com/mongmong/namo/data/local/dao/DiaryDao.kt
  app/src/main/java/com/mongmong/namo/data/remote/auth/LoginView.kt
  app/src/main/java/com/mongmong/namo/data/remote/category/CategoryService.kt
  app/src/main/java/com/mongmong/namo/data/remote/category/CategoryView.kt
  app/src/main/java/com/mongmong/namo/data/remote/diary/DiaryRepository.kt
  app/src/main/java/com/mongmong/namo/data/remote/diary/DiaryService.kt
  app/src/main/java/com/mongmong/namo/data/remote/diary/DiaryView.kt
  app/src/main/java/com/mongmong/namo/data/remote/schedule/GetAllMoimScheduleView.kt
  app/src/main/java/com/mongmong/namo/data/remote/schedule/ScheduleService.kt
  app/src/main/java/com/mongmong/namo/data/remote/schedule/ScheduleView.kt
  app/src/main/java/com/mongmong/namo/domain/model/Diary.kt
  app/src/main/java/com/mongmong/namo/domain/usecase/GetCategoriesUseCase.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/MainActivity.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/category/CategorySettingFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/custom/CustomSettingFragment.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/DiaryAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/diary/adapter/MoimDiaryAdapter.kt
  app/src/main/java/com/mongmong/namo/presentation/ui/group/diary/MoimDiaryActivity.kt
Labels: ♻️ refactor
